---
- name: Installing Docker, Nomad, Consul Playbook
  hosts: all
  remote_user: ubuntu
  become: true
  tasks:






 # - name: Update all packages to their latest version
 #   apt:
 #     name: "*"
 #     state: latest

  - name: Add Hashicorp Official GPG key
    shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    args:
      warn: false

  - name: Add Docker GPG Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
        
  - name: Download Nomad Job File
    shell: wget https://raw.githubusercontent.com/mjhfvi/Ansible-Examples/main/aws/nginx.nomad
    args:
      warn: false

  - name: Add Hashicorp Repository to APT Sources
    shell: "echo deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main > /etc/apt/sources.list.d/hashicorp.list"

  - name: Add Docker Repository to APT Sources
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update APT cache
    become: true
    become_user: root
    apt:
      update_cache: yes

  - name: Update APT and Install Nomad, Consul, Docker Packages 
    apt:
      pkg:
      - consul
      - nomad
      - docker-ce
      - python3
      - python3-pip
 
  - name: Install Docker Module for Python
    pip:
      name: 
      - docker-py
      - python-nomad

  - name: Start nomad Service 
    ansible.builtin.service:
     name: nomad
     state: started

  - name: Pause for 5 seconds
    pause:
      seconds: 5

  - name: Run Nomad Job
    shell: nomad run nginx.nomad
    ignore_errors: True
